CREATE TABLE "course_subjects" (
	"code" text PRIMARY KEY NOT NULL,
	"name_en" text NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL
);
--> statement-breakpoint
-- Seed the database from the official CUHK AQS subject catalog snapshot.
-- Future refreshes come from tools/scraper/scrape_courses.py -> pnpm ingest:courses.
INSERT INTO "course_subjects" ("code", "name_en") VALUES
	('ACCT', 'Accountancy'),
	('ACPY', 'Anatomical & Cellular Patholog'),
	('AENP', 'Advanced Emergency Nursing Pra'),
	('AEPT', 'Adv Environmental Planning Tec'),
	('AIMS', 'Artificial Intelligence'),
	('AIST', 'AI: Systems & Tech'),
	('ANAT', 'Anatomy'),
	('ANIC', 'Anaesthesia & Intensive Care'),
	('ANTH', 'Anthropology'),
	('APEP', 'Applied Epidemiology'),
	('ARAB', 'Arabic'),
	('ARCH', 'Architectural Studies'),
	('ARTS', 'Courses offered by Arts Fac'),
	('ASEI', 'Aero Sci and Earth Info & X'),
	('BAMS', 'Courses offered by Fac of BA'),
	('BASA', 'General Business Administratio'),
	('BBMS', 'Biochemical & Biomedical Sci'),
	('BCHE', 'Biochemistry'),
	('BCHM', 'Biochemistry (Medicine)'),
	('BCJC', 'Jointly offered-Dpt of CHI/BCM'),
	('BCME', 'Chinese Medicine'),
	('BECE', 'Early Childhood Education'),
	('BEHM', 'Biotech, Entrep & Healthc Mgt'),
	('BEST', 'Bio, Env Mgt, Sustn & Tech'),
	('BIOL', 'Biology'),
	('BIOS', 'Biostatistics'),
	('BMBL', 'Bimodal Bilingual Studies'),
	('BMED', 'Maths & Maths Education'),
	('BMEG', 'Biomedical Engineering'),
	('BMJC', 'Jointly offered-Bio Pg Com/SBS'),
	('BSCG', 'Gerontology'),
	('BUDS', 'Buddhist Studies'),
	('CCNU', 'Critical Care Nursing'),
	('CCSS', 'Contemporary China Studies'),
	('CDAS', 'Computational Data Science'),
	('CENG', 'Computer Engineering'),
	('CGEN', 'Clinical Gerontology & ELC'),
	('CHCU', 'Chinese Culture'),
	('CHED', 'Early Childhood Education'),
	('CHEM', 'Chemistry'),
	('CHES', 'Chinese Studies'),
	('CHLL', 'Chinese Language & Literature'),
	('CHLT', 'Chinese Proficiency Courses'),
	('CHPR', 'Community Health Practice'),
	('CHPY', 'Chemical Pathology'),
	('CLCC', 'Cantonese'),
	('CLCE', 'CLC content courses'),
	('CLCH', 'Hokkien'),
	('CLCP', 'Putonghua'),
	('CLED', 'Chinese Language Education'),
	('CLGY', 'Clinical Gerontology'),
	('CMBI', 'Cell & Molecular Biology'),
	('CMSC', 'Computer Science (TPg)'),
	('CNGT', 'Medical Genetics'),
	('CODS', 'Communication Disorders and Sc'),
	('COMM', 'Communication'),
	('COOP', 'Co-operative Education'),
	('CSCI', 'Computer Science'),
	('CULS', 'Cultural Studies'),
	('CUMT', 'Cultural Management'),
	('CURE', 'Cultural & Religious Studies'),
	('CVSM', 'Cardiology'),
	('DBAC', 'DBA (Chinese) Programme'),
	('DIUS', 'Diagnostic Ultrasonography'),
	('DOTE', 'Dept of Decis, Oper & Tech'),
	('DROI', 'Diagnostic Radiology & Organ I'),
	('DSME', 'Decision Sciences & Managerial'),
	('DSPS', 'Data Science & Policy Studies'),
	('EASC', 'Earth and Atmospheric Sciences'),
	('ECLT', 'E-Commerce (Business Programme'),
	('ECON', 'Economics'),
	('ECTM', 'Ecotourism'),
	('EDUC', 'Education'),
	('EEEN', 'Energy and Environmental Erg'),
	('EESC', 'Earth & Environmental Sci'),
	('EIHP', 'MSc Env Info, Health & Pub Mgt'),
	('ELED', 'English Language Education'),
	('ELEG', 'Electronic Engineering'),
	('ELTU', 'English Language Teaching Unit'),
	('EMBA', 'Executive MBA'),
	('EMBF', 'EMBA Finance'),
	('ENGE', 'English'),
	('ENGG', 'Courses offered by Fac of Erg'),
	('ENLC', 'End-of-Life Care'),
	('ENLT', 'English Language Teaching'),
	('ENSC', 'Environmental Science'),
	('EPBI', 'Epidemiology & Biostatistics'),
	('EPID', 'Epidemiology of Infectious Dis'),
	('EPIN', 'Entrepreneurship & Innovation'),
	('EPSY', 'Prof Educational Psychology'),
	('ESGS', 'Earth System and GeoInfo Sci'),
	('ESSC', 'Earth System Science-UG Major'),
	('ESTR', 'Courses for ELITE Stream'),
	('EXSC', 'Exercise Science'),
	('FAAS', 'Fine Arts'),
	('FAME', 'Family Medicine'),
	('FINA', 'Finance'),
	('FNSC', 'Food & Nutritional Sciences'),
	('FREN', 'French'),
	('FTEC', 'Financial Technology'),
	('GAST', 'Gastroenterology'),
	('GDRS', 'Gender Studies'),
	('GECC', 'GE - Chung Chi College'),
	('GECW', 'GE - CW Chu College'),
	('GEJC', 'GE - Joint Colleges'),
	('GEMC', 'GE - Morningside College'),
	('GENA', 'GE - New Asia College'),
	('GEOR', 'Geriatric Orthopaedics'),
	('GERM', 'German'),
	('GESC', 'GE - Shaw College'),
	('GESH', 'GE - S.H. Ho College'),
	('GEUC', 'GE - United College'),
	('GEWS', 'GE - Lee Woo Sing College'),
	('GEYS', 'GE - Wu Yee Sun College'),
	('GISM', 'Geoinformation Science'),
	('GLBS', 'Global Studies (2-year)'),
	('GLEF', 'Global Economics and Finance'),
	('GLOF', 'Global Finance'),
	('GLSD', 'Global Studies'),
	('GNBF', 'Genomics and Bioinformatics'),
	('GNED', 'General Education'),
	('GPAD', 'Government & Public Admin'),
	('GPEC', 'Global Political Economy'),
	('GPGC', 'Govt & Poli (Greater Chi)'),
	('GPSU', 'Global Physician-Leadership St'),
	('GRMD', 'Geography & Resource Mgt'),
	('GRON', 'Gerontology'),
	('HIST', 'History'),
	('HKSL', 'Hong Kong Sign Language'),
	('HPSB', 'Master of Public Health'),
	('HSGS', 'Housing Studies'),
	('HSOC', 'Health Sociomedical Sciences'),
	('HSYS', 'Health Systems'),
	('HTMG', 'Hotel And Tourism Management'),
	('IASP', 'International Asian Studies'),
	('IBBA', 'Integrated BBA Programme'),
	('IEMS', 'Information Engineering (TPg)'),
	('IERG', 'Information Engineering'),
	('IMSC', 'Artic BSc PhD Pgm in Math Sci'),
	('INDA', 'Interdis Data Analytics'),
	('INFD', 'Infectious Diseases'),
	('ITAL', 'Italian'),
	('JASP', 'Japanese Studies'),
	('KORE', 'Korean'),
	('LAWS', 'Law'),
	('LDTE', 'Learning Design and Technology'),
	('LING', 'Linguistics'),
	('LSCI', 'Life Sciences Courses'),
	('LSCM', 'Logistics & Supply Chain Mgt'),
	('LSED', 'Liberal Studies'),
	('MAED', 'Mathematics Education'),
	('MAEG', 'Mechanical & Automation Engg'),
	('MAPE', 'Parent Education'),
	('MASE', 'Materials Sci & Erg'),
	('MATH', 'Mathematics'),
	('MAVE', 'Values Education'),
	('MBAC', 'MBA Programmes'),
	('MBTE', 'Molecular Biotechnology'),
	('MCLE', 'Chinese Lang Education (TPg)'),
	('MCLS', 'Curriculum Dev& Teaching of LS'),
	('MCNS', 'Stroke & Clinical Neuroscience'),
	('MECM', 'Early Childhood Education'),
	('MEDF', 'Medicine Faculty Package'),
	('MEDM', 'Endo, Diabetes & Metabolism'),
	('MEDP', 'Molecular Med & Biostatistics'),
	('MEDU', 'Medicine'),
	('MESC', 'Medical Sciences (PG)'),
	('MFMD', 'Maternal Fetal Medicine'),
	('MGNT', 'Management'),
	('MHLS', 'Mental Health'),
	('MICY', 'Microbiology'),
	('MIEG', 'MIEG'),
	('MITE', 'Information Technology in Educ'),
	('MKTG', 'Marketing'),
	('MLSC', 'Medical Laboratory Sciences'),
	('MMAT', 'Mathematics (TPg)'),
	('MPTE', 'Putonghua Education'),
	('MPUP', 'Public Policy'),
	('MRGO', 'Musculo Med, Rehab & Ger Orth'),
	('MSAE', 'Student Activities in Edu'),
	('MSEG', 'Materials Sci & Engineering'),
	('MSMR', 'Musculoskeletal Med & Rehab'),
	('MTCI', 'Teaching Chi as Int''l Lang'),
	('MUSC', 'Music'),
	('NSCI', 'Natural Sciences'),
	('NSSC', 'Neurological Sciences'),
	('NURS', 'Nursing'),
	('OBGY', 'Obstetrics & Gynaecology'),
	('OBSC', 'Obstetric Care'),
	('OENV', 'Occupational & Environmental H'),
	('OMBA', 'OneMBA'),
	('ORLC', 'Otorhinol, Head & Neck Surgery'),
	('ORTY', 'Orthopaedics & Traumatology'),
	('OVSC', 'Ophthalmology & Visual Science'),
	('PBHT', 'Public Heatlh (TPg)'),
	('PEDU', 'Education (PG)'),
	('PGDC', 'PgD Education (ECE)'),
	('PGDE', 'PgD Education'),
	('PGDP', 'PgD Education (Primary)'),
	('PHAR', 'Pharmacy'),
	('PHEC', 'Prehospital and Emergency Care'),
	('PHED', 'Physical Education'),
	('PHIL', 'Philosophy'),
	('PHMA', 'Pharmacology'),
	('PHPC', 'Public Health'),
	('PHUG', 'Public Health (Ug)'),
	('PHYS', 'Physics'),
	('PHYY', 'Physiology'),
	('POPG', 'Public Heatlh (TPg)'),
	('POPN', 'Perio Care of Min Acc Sur'),
	('PRHC', 'Primary Healthcare'),
	('PSYC', 'Psychology'),
	('PUBH', 'Public Health (RPg)'),
	('REES', 'MSc Real Estate'),
	('RELS', 'Religious Studies & Theology'),
	('RMCE', 'Reprod Med & Clin Embry'),
	('RMED', 'Research Medicine'),
	('RMSC', 'Risk Management Science'),
	('ROSE', 'Robotics'),
	('RUSS', 'Russian'),
	('SBMS', 'Biomedical Sciences'),
	('SEEM', 'Systems Engineering & Engg Mgt'),
	('SENV', 'Sustainable & Environmental De'),
	('SGCL', 'School Guidance & Counselling'),
	('SILP', 'School Improvement and Leaders'),
	('SLPA', 'Speech-Language Pathology'),
	('SOCI', 'Sociology'),
	('SOSC', 'Courses offered by SSc Faculty'),
	('SOWK', 'Social Work'),
	('SPAN', 'Spanish'),
	('SPED', 'Sports Science & Physical Educ'),
	('SPSY', 'Sports Studies'),
	('SSMU', 'Selected Study Modules'),
	('SSPA', 'MSc Sports Sci & Phy Activity'),
	('SSPE', 'Sports Sci & Phy Edu (TPg)'),
	('STAR', 'Courses for STAR Stream'),
	('STAT', 'Statistics'),
	('SURY', 'Surgery'),
	('SUTM', 'Sustainable Tourism'),
	('TESL', 'Teach Eng Spkrs Oth Langs'),
	('THAI', 'Thai'),
	('THEO', 'Theology'),
	('TRAN', 'Translation'),
	('UGCP', 'China Programme'),
	('UGEA', 'Chinese Cultural Heritage'),
	('UGEB', 'Nature, Science and Technology'),
	('UGEC', 'Society and Culture'),
	('UGED', 'Self and Humanity'),
	('UGFH', 'In Dialogue with Humanity'),
	('UGFN', 'In Dialogue with Nature'),
	('URBD', 'Urban Design'),
	('URSP', 'Urban Studies'),
	('WOHS', 'Women''s Health Studies'),
	('XCBS', 'Unit Exemption (CBS)'),
	('XCCS', 'Unit Exemption (CCSS/CHES)'),
	('XFUD', 'Unit Exemption (SJTU)'),
	('XUNC', 'Unit Exemption (UNC)'),
	('XUSC', 'Unit Exemption (USC)'),
	('XWAS', 'Unit Exemption (Waseda)')
ON CONFLICT ("code") DO UPDATE SET
	"name_en" = excluded."name_en",
	"updated_at" = now();
