ALTER TABLE "accounts" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "achievement_catalogs" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "achievement_evidence" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "achievement_fusion_recipes" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "achievement_fusion_sources" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "achievement_notices" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "achievement_profiles" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "achievement_rules" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "admin_audit_logs" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "announcements" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "build_items" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "builds" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "campus_bus_arrival_event_observations" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "campus_bus_arrival_events" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "campus_bus_arrival_observations" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "campus_bus_feedback_rate_limits" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "campus_bus_prediction_adjustments" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "campus_bus_prediction_model_revisions" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "campus_bus_trip_match_candidates" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "canteen_dish_comments" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "canteen_dish_votes" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "canteen_menu_item_prices" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "canteen_menu_items" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "canteen_menu_sources" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "canteen_menu_sync_runs" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "canteen_ordering_handoffs" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "canteen_shame_votes" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "canteens" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "category_courses" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "course_aliases" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "course_enrollments" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "course_offering_instructors" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "course_ratings" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "course_review_likes" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "course_review_replies" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "course_reviews" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "course_subjects" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "courses" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "danmaku_messages" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "discussions" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "major_categories" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "majors" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "menu_import_drafts" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "notifications" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "product_updates" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "professor_courses" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "professor_staff_identities" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "professors" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "sessions" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "site_settings" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "staff_affiliation_titles" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "staff_affiliations" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "staff_aliases" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "staff_departments" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "staff_organisation_affiliations" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "staff_organisations" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "staff_people" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "staff_person_sources" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "staff_teaching_assignments" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "takeout_menu_item_prices" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "takeout_menu_items" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "takeouts" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "user_achievements" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "user_hidden_achievements" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "users" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "verifications" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "wiki_drafts" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "wiki_links" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "wiki_pages" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "wiki_revisions" ENABLE ROW LEVEL SECURITY;