ALTER TABLE "campus_map_building_provenance" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "campus_map_buildings" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "campus_map_changesets" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "campus_map_contributor_blocks" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "campus_map_current_facts" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "campus_map_current_revisions" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "campus_map_fact_revisions" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "campus_map_fact_schemas" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "campus_map_floor_provenance" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "campus_map_floors" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "campus_map_moderation_cases" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "campus_map_moderation_decisions" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "campus_map_moderation_requests" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "campus_map_note_event_visibility" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "campus_map_note_events" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "campus_map_note_outbox" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "campus_map_note_rate_limits" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "campus_map_note_requests" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "campus_map_note_subscriptions" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "campus_map_note_visibility" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "campus_map_notes" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "campus_map_place_changes" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "campus_map_places" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "campus_map_provenance_sources" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "campus_map_provider_mapping_events" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "campus_map_provider_mapping_requests" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "campus_map_provider_mappings" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "campus_map_publish_rate_limits" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "campus_map_publish_requests" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "campus_map_reports" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "campus_map_revision_provenance" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "campus_map_revision_visibility" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "notifications" ENABLE ROW LEVEL SECURITY;