#!/usr/bin/env bash
#
# A wizard — walks a human through a manual procedure step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library — delightful, consistent UX. Identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear — wipe the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" — opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later — it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" — clear the screen, then announce a stage and show progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." — a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." — a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL — open in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser — visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser — visit it manually: $url"
}

# pause "msg" — wait for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" — y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY — current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" — read a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" — like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE — upsert KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE — set a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name — gh not ready; set it later"
}

# set_var NAME VALUE — set a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name — gh not ready; set it later"
}

# finish — clear, then a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES — author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=6

# Never allow an inherited or command-line xtrace mode to print the bearer.
set +x

REPOSITORY="HomuraCatMadoka/CUpedia"
SUPABASE_PROJECT_REF="lisyyhruzlenzcehykrz"
SUPABASE_PROJECT_NAME="cupedia-sg"
SUPABASE_VAULT_URL="https://supabase.com/dashboard/project/${SUPABASE_PROJECT_REF}/integrations"
SUPABASE_DATA_API_URL="https://supabase.com/dashboard/project/${SUPABASE_PROJECT_REF}/integrations/data_api/settings"
VERCEL_SCOPE="danhuang-s-projects"
VERCEL_PROJECT="cupedia"
VERCEL_PRODUCTION_ALIAS="cupedia-danhuang-s-projects.vercel.app"
ROLLOUT_COMMIT="5dccbe512febd9f93ae5233cbd8bfe863de6b9c5"
VAULT_SECRET_NAME="cupedia_canteen_menu_sync_bearer"
MODE="${1:-rollout}"
SCRIPT_DIR=$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)
REPO_ROOT=$(cd "$SCRIPT_DIR/.." && pwd)
ROLLOUT_CONTRACT_SCRIPT="$REPO_ROOT/scripts/lib/canteen-menu-sync-rollout-contract.mjs"
SUPABASE_WORKDIR=""
VERCEL_WORKDIR=""
MENU_SYNC_TRIGGER_SECRET=""

clearClipboard() {
  if command -v pbcopy >/dev/null 2>&1; then
    printf '' | pbcopy
  elif command -v wl-copy >/dev/null 2>&1; then
    printf '' | wl-copy
  elif command -v xclip >/dev/null 2>&1; then
    printf '' | xclip -selection clipboard
  fi
}

cleanupRollout() {
  MENU_SYNC_TRIGGER_SECRET=""
  unset MENU_SYNC_TRIGGER_SECRET
  clearClipboard || true
  if [[ "$SUPABASE_WORKDIR" == /tmp/cupedia-764-supabase.* && -d "$SUPABASE_WORKDIR" ]]; then
    rm -rf -- "$SUPABASE_WORKDIR"
  fi
  if [[ "$VERCEL_WORKDIR" == /tmp/cupedia-764-vercel.* && -d "$VERCEL_WORKDIR" ]]; then
    rm -rf -- "$VERCEL_WORKDIR"
  fi
}
trap cleanupRollout EXIT

requireCommand() {
  local command_name="$1"
  if ! command -v "$command_name" >/dev/null 2>&1; then
    warn "required command is missing: $command_name"
    exit 1
  fi
}

copySecret() {
  local value="$1"
  if command -v pbcopy >/dev/null 2>&1; then
    printf '%s' "$value" | pbcopy
  elif command -v wl-copy >/dev/null 2>&1; then
    printf '%s' "$value" | wl-copy
  elif command -v xclip >/dev/null 2>&1; then
    printf '%s' "$value" | xclip -selection clipboard
  else
    return 1
  fi
}

askEphemeralSecret() {
  local key="$1" prompt="$2" input=""
  printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  read -rs input || true
  printf '\n'
  printf -v "$key" '%s' "$input"
}

setRepositorySecret() {
  local name="$1" value="$2"
  if printf '%s' "$value" | gh secret set "$name" --repo "$REPOSITORY" >/dev/null; then
    WRITTEN_SECRET+=("$name")
    printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
    return 0
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name --repo $REPOSITORY)")
  warn "GitHub secret $name could not be updated"
  return 1
}

assertNoMenuSyncRun() {
  local running_count
  running_count=$(gh run list \
    --repo "$REPOSITORY" \
    --workflow canteen-menu-sync.yml \
    --limit 20 \
    --json status \
    --jq '[.[] | select(.status == "in_progress" or .status == "queued")] | length')
  if [[ "$running_count" != "0" ]]; then
    warn "a production menu-sync workflow is queued or running; retry after it finishes"
    exit 1
  fi
}

assertRotationGap() {
  local minutes_to_tick minutes_from_tick
  IFS=$'\t' read -r minutes_from_tick minutes_to_tick \
    < <(node "$ROLLOUT_CONTRACT_SCRIPT" github-gap)
  if (( minutes_from_tick < 5 )); then
    warn "the previous GitHub wake was only ${minutes_from_tick} minute(s) ago; wait for delayed runs to appear and finish"
    exit 1
  fi
  if (( minutes_to_tick < 20 )); then
    warn "the next GitHub wake is only ${minutes_to_tick} minute(s) away; retry after that run finishes"
    exit 1
  fi
}

assertOutsidePrimaryWindow() {
  local in_primary_window
  in_primary_window=$(node <<'NODE'
const now = new Date();
const hour = now.getUTCHours();
const minute = now.getUTCMinutes();
const primaryHour = hour === 0 || hour === 3 || hour === 9;
process.stdout.write(primaryHour && minute >= 17 && minute <= 32 ? 'yes' : 'no');
NODE
)
  if [[ "$in_primary_window" == "yes" ]]; then
    warn "current time is inside a Supabase primary minute-17-to-32 window"
    exit 1
  fi
}

supabaseQuery() {
  supabase db query \
    --workdir "$SUPABASE_WORKDIR" \
    --linked \
    --output json \
    "$1"
}

readSchedulerState() {
  # pg_net exposes this as a void function: success means the call completes,
  # while an unhealthy worker raises an exception. Run it separately so we do
  # not mistake PostgreSQL's non-NULL void sentinel for a failed check.
  supabaseQuery "SELECT net.check_worker_is_up();" >/dev/null
  supabaseQuery "
    SELECT activation.environment,
           activation.active AS scheduler_active,
           activation.activated_at,
           job.active AS job_active,
           job.jobid,
           job.schedule,
           job.command,
           job.database,
           current_database() AS current_database,
           job.username,
           current_setting('cron.timezone') AS cron_timezone,
           current_setting('pg_net.ttl', true) AS pg_net_ttl,
           extract(epoch FROM current_setting('pg_net.ttl', true)::interval)::integer
             AS pg_net_ttl_seconds,
           true AS worker_check_completed,
           (SELECT count(*)::integer FROM net.http_request_queue) AS pending_requests,
           (SELECT count(*)::integer FROM vault.secrets WHERE name = '${VAULT_SECRET_NAME}') AS vault_secret_count
    FROM canteen_menu_scheduler.activation AS activation
    JOIN cron.job AS job
      ON job.jobname = 'cupedia-canteen-menu-sync-wakeup'
    WHERE activation.singleton;
  "
}

readVaultMetadata() {
  supabaseQuery "
    SELECT id::text, name, created_at, updated_at
    FROM vault.secrets
    WHERE name = '${VAULT_SECRET_NAME}'
    ORDER BY created_at;
  "
}

readTransportBoundary() {
  supabaseQuery "
    SELECT
      (SELECT count(*)::integer
       FROM pg_extension
       WHERE extname IN ('pg_cron', 'pg_net', 'supabase_vault'))
        AS extension_count,
      (SELECT count(*)::integer
       FROM pg_roles
       WHERE rolname IN ('anon', 'authenticated')) AS client_role_count,
      (SELECT bool_and(NOT rolcanlogin)
       FROM pg_roles
       WHERE rolname IN ('anon', 'authenticated')) AS client_roles_no_login,
      (SELECT count(*)::integer
       FROM pg_class AS class
       JOIN pg_namespace AS namespace ON namespace.oid = class.relnamespace
       WHERE namespace.nspname = 'net'
         AND class.relname IN ('http_request_queue', '_http_response'))
        AS transport_table_count,
      (SELECT bool_and(class.relpersistence = 'u')
       FROM pg_class AS class
       JOIN pg_namespace AS namespace ON namespace.oid = class.relnamespace
       WHERE namespace.nspname = 'net'
         AND class.relname IN ('http_request_queue', '_http_response'))
        AS transport_tables_unlogged,
      (SELECT array_agg(column_name::text ORDER BY ordinal_position) = ARRAY[
         'id',
         'expected_tick_at',
         'sync_window_key',
         'cron_run_id',
         'request_id',
         'request_created_at',
         'http_status',
         'delivery_error',
         'endpoint_disposition',
         'business_code',
         'completed_at'
       ]::text[]
       FROM information_schema.columns
       WHERE table_schema = 'canteen_menu_scheduler'
         AND table_name = 'delivery_audit') AS scheduler_audit_columns_exact;
  "
}

assertTransportBoundary() {
  local transport_boundary
  transport_boundary=$(readTransportBoundary)
  if ! jq -e '
    .rows | length == 1 and
    .[0].extension_count == 3 and
    .[0].client_role_count == 2 and
    .[0].client_roles_no_login and
    .[0].transport_table_count == 2 and
    .[0].transport_tables_unlogged and
    .[0].scheduler_audit_columns_exact
  ' >/dev/null <<<"$transport_boundary"; then
    warn "Supabase extensions or the private pg_net transport boundary differ from the reviewed state"
    jq '.rows' <<<"$transport_boundary"
    exit 1
  fi
}

assertNoReviewRequiredSources() {
  local explicit_review recent_retry_limits
  explicit_review=$(supabaseQuery "
    SELECT id, provider, external_store_id, last_error_code
    FROM public.canteen_menu_sources
    WHERE enabled
      AND last_error_code IS NOT NULL
      AND (
        last_error_code LIKE 'INVALID_%'
        OR last_error_code IN (
          'MENU_SYNC_CONFLICT',
          'MENU_SYNC_IDENTITY_CHURN',
          'MENU_SYNC_SUSPICIOUS_DROP'
        )
      )
    ORDER BY provider, external_store_id;
  ")
  if ! jq -e '.rows | length == 0' >/dev/null <<<"$explicit_review"; then
    warn "an enabled source has an explicit review-required error"
    jq '.rows' <<<"$explicit_review"
    exit 1
  fi

  recent_retry_limits=$(supabaseQuery "
    WITH classified_runs AS (
      SELECT
        source.id AS source_id,
        source.provider,
        source.external_store_id,
        run.status,
        run.error_code,
        run.started_at,
        (run.started_at AT TIME ZONE 'Asia/Hong_Kong')::date AS hkt_date,
        CASE
          WHEN extract(hour FROM run.started_at AT TIME ZONE 'Asia/Hong_Kong') < 11
            THEN 'breakfast'
          WHEN extract(hour FROM run.started_at AT TIME ZONE 'Asia/Hong_Kong') < 17
            THEN 'lunch'
          ELSE 'dinner'
        END AS meal_period
      FROM public.canteen_menu_sync_runs AS run
      JOIN public.canteen_menu_sources AS source
        ON source.id = run.menu_source_id
      WHERE source.enabled
        AND run.started_at >= now() - interval '24 hours'
    ),
    latest_success AS (
      SELECT
        source_id,
        hkt_date,
        meal_period,
        max(started_at) AS started_at
      FROM classified_runs
      WHERE status IN ('applied', 'unchanged')
      GROUP BY source_id, hkt_date, meal_period
    )
    SELECT
      run.provider,
      run.external_store_id,
      run.hkt_date,
      run.meal_period,
      count(*)::integer AS failures_after_latest_success,
      array_agg(run.error_code ORDER BY run.started_at) AS error_codes
    FROM classified_runs AS run
    LEFT JOIN latest_success AS success
      ON success.source_id = run.source_id
     AND success.hkt_date = run.hkt_date
     AND success.meal_period = run.meal_period
    WHERE run.status = 'failed'
      AND coalesce(run.error_code, '') <> 'MENU_SYNC_SUPERSEDED'
      AND (success.started_at IS NULL OR run.started_at > success.started_at)
    GROUP BY
      run.source_id,
      run.provider,
      run.external_store_id,
      run.hkt_date,
      run.meal_period
    HAVING count(*) >= 3
    ORDER BY
      run.hkt_date DESC,
      run.meal_period,
      run.provider,
      run.external_store_id;
  ")
  if ! jq -e '.rows | length == 0' >/dev/null <<<"$recent_retry_limits"; then
    warn "a source reached the retry limit after its latest success in a recent meal window"
    jq '.rows' <<<"$recent_retry_limits"
    exit 1
  fi
}

prepareConnections() {
  for required in gh jq curl node openssl supabase vercel; do
    requireCommand "$required"
  done
  gh auth status >/dev/null
  vercel whoami >/dev/null

  SUPABASE_WORKDIR=$(mktemp -d /tmp/cupedia-764-supabase.XXXXXX)
  supabase init --workdir "$SUPABASE_WORKDIR" --yes >/dev/null
  supabase link \
    --workdir "$SUPABASE_WORKDIR" \
    --project-ref "$SUPABASE_PROJECT_REF" \
    --yes >/dev/null

  VERCEL_WORKDIR=$(mktemp -d /tmp/cupedia-764-vercel.XXXXXX)
  vercel link \
    --cwd "$VERCEL_WORKDIR" \
    --project "$VERCEL_PROJECT" \
    --scope "$VERCEL_SCOPE" \
    --yes >/dev/null
}

assertMainAndProductionDeployment() {
  local compare_status deployment deployment_sha deployment_state

  main_sha=$(gh api "repos/${REPOSITORY}/commits/main" --jq .sha)
  compare_status=$(gh api \
    "repos/${REPOSITORY}/compare/${ROLLOUT_COMMIT}...${main_sha}" \
    --jq .status)
  if [[ "$compare_status" != "identical" && "$compare_status" != "ahead" ]]; then
    warn "main does not contain rollout commit ${ROLLOUT_COMMIT}"
    exit 1
  fi

  workflow_text=$(gh api \
    -H 'Accept: application/vnd.github.raw+json' \
    "repos/${REPOSITORY}/contents/.github/workflows/canteen-menu-sync.yml?ref=main")
  if ! printf '%s' "$workflow_text" | \
    node "$ROLLOUT_CONTRACT_SCRIPT" validate-workflow; then
    warn "main does not contain the reviewed delayed fallback schedules"
    exit 1
  fi

  deployment=$(vercel list "$VERCEL_PROJECT" \
    --scope "$VERCEL_SCOPE" \
    --environment production \
    --format json 2>/dev/null | jq -c \
      'if type == "array" then .[0] else .deployments[0] end')
  deployment_sha=$(jq -r '.meta.githubCommitSha // empty' <<<"$deployment")
  deployment_state=$(jq -r '.state // .readyState // empty' <<<"$deployment")
  if [[ "$deployment_state" != "READY" || "$deployment_sha" != "$main_sha" ]]; then
    warn "Vercel Production is not Ready on the current main commit"
    jq '{url, state, readyState, commit: .meta.githubCommitSha}' <<<"$deployment"
    exit 1
  fi
}

readIssueGateState() {
  local issue757_state issue763_state
  issue757_state=$(gh issue view 757 --repo "$REPOSITORY" --json state --jq .state)
  issue763_state=$(gh issue view 763 --repo "$REPOSITORY" --json state --jq .state)
  if [[ "$issue757_state" != "OPEN" ]]; then
    warn "issue #757 must remain open during rollout and observation"
    exit 1
  fi
  production_recovery_clean=false
  if [[ "$issue763_state" == "CLOSED" ]]; then
    production_recovery_clean=true
  fi
}

verifyFirstNaturalWindow() {
  local active_state activated_at bounds window_start health_to fallback_from
  local fallback_to verify_after window_hkt now_epoch verify_epoch
  local delivery_health window_health fallback_runs fallback_run fallback_run_id
  local fallback_run_url fallback_sha fallback_compare fallback_logs vercel_logs
  local evidence_comment

  assertMainAndProductionDeployment
  readIssueGateState
  assertTransportBoundary
  active_state=$(readSchedulerState)
  if ! jq -e '
    .rows | length == 1 and
    .[0].environment == "production" and
    .[0].scheduler_active and
    .[0].job_active and
    .[0].vault_secret_count == 1
  ' >/dev/null <<<"$active_state"; then
    warn "the reviewed production scheduler is not active"
    jq '.rows' <<<"$active_state"
    exit 1
  fi

  activated_at=$(jq -r '.rows[0].activated_at // empty' <<<"$active_state")
  bounds=$(node "$ROLLOUT_CONTRACT_SCRIPT" first-primary-window "$activated_at")
  IFS=$'\t' read -r window_start health_to fallback_from fallback_to verify_after window_hkt <<<"$bounds"
  now_epoch=$(date +%s)
  verify_epoch=$(node -e 'process.stdout.write(String(Date.parse(process.argv[1]) / 1000))' "$verify_after")
  if (( now_epoch < verify_epoch )); then
    warn "the first natural primary window has not finished its fallback observation period"
    note "first primary starts ${window_hkt} HKT; rerun with: scripts/issue-764-production-rollout-wizard.sh verify"
    exit 1
  fi

  delivery_health=$(supabaseQuery "
    SELECT classification, count(*)::integer AS count
    FROM canteen_menu_scheduler.delivery_health(
      '${window_start}'::timestamptz,
      '${health_to}'::timestamptz
    )
    GROUP BY classification
    ORDER BY classification;
  ")
  if ! jq -e '
    ([.rows[].count] | add) == 16 and
    all(.rows[]; .classification == "primary-progress" or .classification == "primary-no-work")
  ' >/dev/null <<<"$delivery_health"; then
    warn "the first primary window contains missing or failed delivery evidence"
    jq '.rows' <<<"$delivery_health"
    exit 1
  fi

  window_health=$(supabaseQuery "
    SELECT *
    FROM canteen_menu_scheduler.window_health(
      '${window_start}'::timestamptz,
      '${health_to}'::timestamptz
    );
  ")
  if ! jq -e '
    .rows | length == 1 and
    .[0].classification == "primary-drained-window" and
    .[0].primary_completed_at != null and
    .[0].required_source_count == .[0].primary_completed_source_count and
    .[0].enqueue_failure_count == 0 and
    .[0].http_failure_count == 0 and
    .[0].endpoint_rejection_count == 0 and
    .[0].provider_failure_count == 0 and
    .[0].retry_later_count == 0 and
    .[0].review_required_count == 0 and
    .[0].inapplicable_run_count == 0
  ' >/dev/null <<<"$window_health"; then
    warn "the first window did not complete through the healthy Supabase primary"
    jq '.rows' <<<"$window_health"
    exit 1
  fi

  fallback_runs=$(gh run list \
    --repo "$REPOSITORY" \
    --workflow canteen-menu-sync.yml \
    --event schedule \
    --limit 50 \
    --json databaseId,createdAt,conclusion,status,url,headSha)
  fallback_run=$(jq -c \
    --arg from "$fallback_from" \
    --arg to "$fallback_to" '
      [.[] | select(
        (.createdAt | fromdateiso8601) >= ($from | fromdateiso8601) and
        (.createdAt | fromdateiso8601) <= ($to | fromdateiso8601)
      )] | sort_by(.createdAt) | .[0] // empty
    ' <<<"$fallback_runs")
  if [[ -z "$fallback_run" ]] || ! jq -e \
    '.status == "completed" and .conclusion == "success"' \
    >/dev/null <<<"$fallback_run"; then
    warn "the delayed GitHub fallback is not yet independently successful"
    [[ -n "$fallback_run" ]] && jq . <<<"$fallback_run"
    exit 1
  fi

  fallback_run_id=$(jq -r .databaseId <<<"$fallback_run")
  fallback_run_url=$(jq -r .url <<<"$fallback_run")
  fallback_sha=$(jq -r .headSha <<<"$fallback_run")
  fallback_compare=$(gh api \
    "repos/${REPOSITORY}/compare/${ROLLOUT_COMMIT}...${fallback_sha}" \
    --jq .status)
  if [[ "$fallback_compare" != "identical" && "$fallback_compare" != "ahead" ]]; then
    warn "the delayed GitHub fallback did not run from a commit containing the rollout baseline"
    exit 1
  fi
  fallback_logs=$(gh run view "$fallback_run_id" --repo "$REPOSITORY" --log)
  if [[ "$fallback_logs" != *'Call 1/16: no-work'* ]]; then
    warn "the delayed GitHub fallback did not record an immediate no-work drain"
    exit 1
  fi
  if grep -Eiq 'authorization:|bearer[[:space:]]|decrypted_secret|MENU_SYNC_TRIGGER_SECRET=' \
    <<<"$fallback_logs"; then
    warn "the delayed GitHub fallback log contains a sensitive-data marker"
    exit 1
  fi

  vercel_logs=$(vercel logs \
    --project "$VERCEL_PROJECT" \
    --scope "$VERCEL_SCOPE" \
    --environment production \
    --since "$window_start" \
    --until "$fallback_to" \
    --query "/api/internal/canteen-menu-sync/next" \
    --limit 500 \
    --json 2>/dev/null)
  if grep -Eiq 'authorization:|bearer[[:space:]]|decrypted_secret|MENU_SYNC_TRIGGER_SECRET=|provider[_ -]?payload|raw[_ -]?response' \
    <<<"$vercel_logs"; then
    warn "the bounded Vercel production logs contain a sensitive-data marker"
    exit 1
  fi

  active_state=$(readSchedulerState)
  if ! jq -e '.rows | length == 1 and .[0].pending_requests == 0' \
    >/dev/null <<<"$active_state"; then
    warn "pg_net still has a pending request after the observation window"
    jq '.rows' <<<"$active_state"
    exit 1
  fi

  evidence_comment=$(jq -rn \
    --arg window_hkt "$window_hkt" \
    --arg deployment "$main_sha" \
    --arg fallback_url "$fallback_run_url" \
    --arg recovery_clean "$production_recovery_clean" \
    --argjson delivery "$(jq '.rows' <<<"$delivery_health")" \
    --argjson window "$(jq '.rows[0]' <<<"$window_health")" '
      "Production rollout evidence (HKT)\n\n" +
      "- Deployment: `" + $deployment + "` (Vercel Production Ready)\n" +
      "- Scheduler: `cupedia-canteen-menu-sync-wakeup`, `17-32 0,3,9 * * *`, active in production\n" +
      "- First natural primary start: " + $window_hkt + " HKT\n" +
      "- Delivery classifications: `" + ($delivery | tostring) + "`\n" +
      "- Window health: `" + ($window | tostring) + "`\n" +
      "- Pending pg_net requests after observation: 0\n" +
      "- Delayed GitHub fallback: " + $fallback_url + " (successful immediate no-work)\n\n" +
      "The runtime scheduler audit schema matched its bounded metadata allowlist, and bounded GitHub/Vercel logs contained no sensitive-data markers. No bearer, authorization header, raw response body, or provider payload was queried or copied into this evidence. #757 was confirmed open. " +
      (if $recovery_clean == "true" then
        "#763 is closed, so the separate seven-day acceptance gate may begin from the reviewed clean recovery point."
       else
        "#763 is still open, so the seven-day acceptance clock has not started."
       end)
  ')

  if confirm "Post this bounded evidence to issue #764?"; then
    printf '%s\n' "$evidence_comment" | gh issue comment 764 \
      --repo "$REPOSITORY" \
      --body-file - >/dev/null
    say "Issue #764 now records the first natural production window."
  else
    warn "verification passed locally, but issue #764 was not updated"
    exit 1
  fi
}

if [[ "$MODE" != "rollout" && "$MODE" != "verify" ]]; then
  printf 'Usage: %s [rollout|verify]\n' "$0" >&2
  exit 2
fi

cd "$REPO_ROOT"

if [[ "$MODE" == "verify" ]]; then
  TOTAL_STAGES=2
  banner "CUpedia · Issue #764 production verification"

  stage "Connect read-only evidence tools"
  say "We reconnect to production without reading or changing any bearer value."
  prepareConnections
  assertMainAndProductionDeployment
  readIssueGateState

  stage "Verify the first natural primary window"
  verifyFirstNaturalWindow
  finish
  exit 0
fi

banner "CUpedia · Issue #764 production rollout"

stage "Safety preflight"
say "We verify every fail-closed boundary before touching credentials."
prepareConnections
assertMainAndProductionDeployment
readIssueGateState

assertNoMenuSyncRun
assertRotationGap
assertOutsidePrimaryWindow

scheduler_state=$(readSchedulerState)
if ! jq -e '
  .rows as $rows |
  ($rows | length == 1) and
  $rows[0].environment == "unconfigured" and
  ($rows[0].scheduler_active | not) and
  ($rows[0].job_active | not) and
  $rows[0].schedule == "17-32 0,3,9 * * *" and
  $rows[0].command == "SELECT canteen_menu_scheduler.enqueue_canteen_menu_sync_wakeup()" and
  $rows[0].database == $rows[0].current_database and
  $rows[0].username == "postgres" and
  (["GMT", "UTC", "Etc/GMT", "Etc/UTC"] | index($rows[0].cron_timezone)) != null and
  $rows[0].pg_net_ttl_seconds > 0 and
  $rows[0].pg_net_ttl_seconds <= 21600 and
  $rows[0].worker_check_completed and
  $rows[0].pending_requests == 0 and
  ($rows[0].vault_secret_count == 0 or $rows[0].vault_secret_count == 1)
' >/dev/null <<<"$scheduler_state"; then
  warn "scheduler installation is not in the reviewed inactive state"
  jq '.rows' <<<"$scheduler_state"
  exit 1
fi

assertTransportBoundary

say "Database scheduler is exact, inactive, queue-empty, and worker-healthy."
assertNoReviewRequiredSources
open_url "$SUPABASE_DATA_API_URL"
step "Sign in to ${SUPABASE_PROJECT_NAME} if needed."
step "Confirm Exposed schemas is exactly public, graphql_public."
step "Stop if net appears anywhere in the exposed-schema list."
if ! confirm "Does the dashboard still show only public and graphql_public?"; then
  warn "Data API boundary was not confirmed; rollout stopped"
  exit 1
fi

stage "Create or rotate the Vault secret"
say "The new bearer stays only in process memory and your clipboard. It is never written to .env."
askEphemeralSecret MENU_SYNC_TRIGGER_SECRET "Paste a new random token, or press Enter to generate one:"
if [[ -z "$MENU_SYNC_TRIGGER_SECRET" ]]; then
  MENU_SYNC_TRIGGER_SECRET=$(openssl rand -base64 48 | tr -d '\n')
  say "Generated a new 48-byte random token."
fi
if [[ ${#MENU_SYNC_TRIGGER_SECRET} -lt 43 || "$MENU_SYNC_TRIGGER_SECRET" =~ [[:space:]] ]]; then
  warn "token must be at least 43 characters with no whitespace"
  exit 1
fi
if ! copySecret "$MENU_SYNC_TRIGGER_SECRET"; then
  warn "no supported clipboard command is available; supply the token yourself on a rerun"
  exit 1
fi

vault_metadata_before=$(readVaultMetadata)
vault_count=$(jq -r '.rows | length' <<<"$vault_metadata_before")
open_url "$SUPABASE_VAULT_URL"
step "Open Vault, then open the Secrets list."
if [[ "$vault_count" == "0" ]]; then
  step "Choose Add new secret."
else
  step "Find ${VAULT_SECRET_NAME} and choose Edit; do not create a duplicate."
fi
step "Use the name ${VAULT_SECRET_NAME}."
step "Paste the clipboard value into Secret. Do not paste it into SQL Editor."
step "Optionally use description: CUpedia production canteen menu sync bearer."
pause "Save the Vault secret, then press Enter to verify metadata."

vault_metadata=$(readVaultMetadata)
vault_transition=$(jq -n \
  --argjson before "$(jq '.rows' <<<"$vault_metadata_before")" \
  --argjson after "$(jq '.rows' <<<"$vault_metadata")" \
  '{before: $before, after: $after}')
if ! printf '%s' "$vault_transition" | \
  node "$ROLLOUT_CONTRACT_SCRIPT" validate-vault-metadata; then
  warn "vault metadata did not change during this rollout"
  jq '{before: (.before | map({id, created_at, updated_at})), after: (.after | map({id, created_at, updated_at}))}' \
    <<<"$vault_transition"
  exit 1
fi
say "Vault metadata shows exactly one named secret; its value was not queried."

stage "Rotate Vercel and GitHub"
say "Vercel is updated and redeployed first. GitHub is switched immediately after the new deployment is Ready."
assertNoMenuSyncRun
assertRotationGap
if ! confirm "Rotate MENU_SYNC_TRIGGER_SECRET in production now?"; then
  warn "credential rotation cancelled; cron remains inactive"
  exit 1
fi
assertNoMenuSyncRun
assertRotationGap

printf '%s' "$MENU_SYNC_TRIGGER_SECRET" | vercel env update \
  MENU_SYNC_TRIGGER_SECRET production \
  --sensitive \
  --yes \
  --cwd "$VERCEL_WORKDIR" \
  --scope "$VERCEL_SCOPE" >/dev/null

deployment_output=$(vercel redeploy \
  "$VERCEL_PRODUCTION_ALIAS" \
  --target production \
  --scope "$VERCEL_SCOPE")
deployment_url=$(printf '%s\n' "$deployment_output" | grep -Eo 'https://[^ ]+\.vercel\.app' | tail -n1)
if [[ -z "$deployment_url" ]]; then
  warn "Vercel redeploy did not return a deployment URL"
  exit 1
fi

deployment_details=$(vercel inspect \
  "$deployment_url" \
  --scope "$VERCEL_SCOPE" \
  --format=json 2>/dev/null)
if ! jq -e '
  .readyState == "READY" and
  .target == "production" and
  (.aliases | index("cupedia.org")) != null
' >/dev/null <<<"$deployment_details"; then
  warn "new Vercel deployment is not Ready on the production alias"
  jq '{url, readyState, target, aliases}' <<<"$deployment_details"
  exit 1
fi

if ! setRepositorySecret MENU_SYNC_TRIGGER_SECRET "$MENU_SYNC_TRIGGER_SECRET"; then
  warn "Vercel has already switched, so scheduled fallback authentication is mismatched; rerun the wizard before the next wake"
  exit 1
fi
clearClipboard || true
say "Vault, Vercel Production, and GitHub Actions now use the same in-memory token."

stage "Post-rotation verification"
say "This stage performs only read-only checks and an unauthenticated 401 probe."

vercel_env_row=$(vercel env ls production \
  --cwd "$VERCEL_WORKDIR" \
  --scope "$VERCEL_SCOPE" 2>&1 | grep 'MENU_SYNC_TRIGGER_SECRET' || true)
if [[ -z "$vercel_env_row" ]]; then
  warn "Vercel no longer lists MENU_SYNC_TRIGGER_SECRET for Production"
  exit 1
fi

github_secret_count=$(gh secret list \
  --repo "$REPOSITORY" \
  --json name \
  --jq '[.[] | select(.name == "MENU_SYNC_TRIGGER_SECRET")] | length')
if [[ "$github_secret_count" != "1" ]]; then
  warn "GitHub does not list exactly one MENU_SYNC_TRIGGER_SECRET"
  exit 1
fi

http_status=$(curl -sS -o /dev/null -w '%{http_code}' \
  -X POST https://cupedia.org/api/internal/canteen-menu-sync/next)
if [[ "$http_status" != "401" ]]; then
  warn "unauthenticated production endpoint returned ${http_status}, expected 401"
  exit 1
fi

scheduler_state=$(readSchedulerState)
if ! jq -e '
  .rows | length == 1 and
  .[0].environment == "unconfigured" and
  (.[0].scheduler_active | not) and
  (.[0].job_active | not) and
  .[0].vault_secret_count == 1 and
  .[0].pending_requests == 0 and
  .[0].worker_check_completed
' >/dev/null <<<"$scheduler_state"; then
  warn "post-rotation scheduler preflight failed"
  jq '.rows' <<<"$scheduler_state"
  exit 1
fi

assertNoReviewRequiredSources

advisor_output=$(supabase db advisors \
  --workdir "$SUPABASE_WORKDIR" \
  --linked \
  --type all \
  --level warn \
  --fail-on none \
  --output-format json)
if ! jq -e '
  (if type == "array" then . else .results end) |
  all(.[];
    (.name == "function_search_path_mutable" and
     .metadata.name == "prevent_campus_bus_arrival_observation_mutation") or
    (.name == "extension_in_public" and .metadata.name == "pg_trgm")
  )
' >/dev/null <<<"$advisor_output"; then
  warn "production advisors contain a new warning"
  jq '(if type == "array" then . else .results end)' <<<"$advisor_output"
  exit 1
fi
say "Credential metadata, inactive scheduler, endpoint guard, and advisors all pass."

stage "Activate Supabase Cron"
warn "This is the production cutover. Issue #757 stays open until #763 is also clean and seven observed days pass."
say "The activation function will re-check the exact job, Vault metadata, UTC timezone, pg_net TTL, and worker."
assertOutsidePrimaryWindow
assertNoMenuSyncRun
assertRotationGap
if ! confirm "Activate cupedia-canteen-menu-sync-wakeup in production?"; then
  warn "activation skipped; all credentials are aligned but cron remains inactive"
  finish
  exit 0
fi
assertOutsidePrimaryWindow
assertNoMenuSyncRun
assertRotationGap
assertNoReviewRequiredSources

activation_result=$(supabaseQuery "SELECT canteen_menu_scheduler.activate() AS result;")
if ! jq -e '.rows | length == 1' >/dev/null <<<"$activation_result"; then
  warn "activation call did not return the expected result"
  exit 1
fi

active_state=$(readSchedulerState)
if ! jq -e '
  .rows | length == 1 and
  .[0].environment == "production" and
  .[0].scheduler_active and
  .[0].job_active and
  .[0].vault_secret_count == 1 and
  .[0].pending_requests == 0
' >/dev/null <<<"$active_state"; then
  warn "activation verification failed; run canteen_menu_scheduler.deactivate() immediately"
  jq '.rows' <<<"$active_state"
  exit 1
fi

say "Supabase Cron is active with the reviewed single-job contract."

stage "Verify the first natural primary window"
say "This read-only stage proves the Cron tick, pg_net delivery, endpoint result, and non-empty business completion agree."
note "If the next window is hours away, exit safely and later run: scripts/issue-764-production-rollout-wizard.sh verify"
pause "Wait until at least 40 minutes after the next 08:17, 11:17, or 17:17 HKT window, then press Enter."
verifyFirstNaturalWindow

finish
