#!/usr/bin/env bash
#
# A wizard — walks a human through a manual procedure step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library — delightful, consistent UX. Identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear — wipe the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" — opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later — it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" — clear the screen, then announce a stage and show progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." — a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." — a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL — open in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser — visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser — visit it manually: $url"
}

# pause "msg" — wait for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" — y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY — current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" — read a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" — like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE — upsert KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE — set a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name — gh not ready; set it later"
}

# set_var NAME VALUE — set a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name — gh not ready; set it later"
}

# finish — clear, then a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES — author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=4
ENV_FILE=/dev/null
REPOSITORY="HomuraCatMadoka/CUpedia"
WORKFLOW="professor-portrait-backfill.yml"

set_production_secret() {
  local name="$1" value="$2"
  if [[ -z "$value" ]]; then
    SKIPPED+=("GitHub production secret $name (no value provided)")
    warn "skipped empty production secret $name"
    return
  fi
  if printf '%s' "$value" | gh secret set "$name" --env production --repo "$REPOSITORY" >/dev/null 2>&1; then
    WRITTEN_SECRET+=("$name")
    printf '  %s✓ set%s GitHub production secret %s\n' "$GREEN" "$RESET" "$name"
    return
  fi
  SKIPPED+=("GitHub production secret $name")
  warn "could not set production secret $name"
  return 1
}

banner "Professor portrait production backfill"

stage "GitHub production environment"
say "This creates only the protected execution boundary; it does not run a backfill."
if ! command -v gh >/dev/null 2>&1 || ! gh auth status >/dev/null 2>&1; then
  warn "GitHub CLI is missing or not authenticated."
  say "Install gh, run 'gh auth login', then restart this wizard."
  exit 1
fi
if ! gh repo view "$REPOSITORY" >/dev/null 2>&1; then
  warn "Your GitHub account cannot access $REPOSITORY."
  exit 1
fi
if confirm "Create or confirm the GitHub production Environment now?"; then
  gh api --method PUT "repos/$REPOSITORY/environments/production" >/dev/null
  printf '  %s✓ ready%s GitHub production Environment\n' "$GREEN" "$RESET"
else
  warn "The workflow cannot run until the production Environment exists."
  exit 1
fi
open_url "https://github.com/$REPOSITORY/settings/environments"
step "Open the production Environment."
step "Under Deployment protection rules, add the intended required reviewer if your GitHub plan supports it."
pause "Press Enter after reviewing the protection settings."
REQUIRED_REVIEWER_COUNT="$(gh api "repos/$REPOSITORY/environments/production" \
  --jq '[.protection_rules[]? | select(.type == "required_reviewers") | .reviewers[]?] | length')"
if [[ ! "$REQUIRED_REVIEWER_COUNT" =~ ^[1-9][0-9]*$ ]]; then
  warn "The production Environment does not have a required reviewer."
  say "Add at least one required reviewer, then restart this wizard."
  exit 1
fi
printf '  %s✓ protected%s by %s required reviewer(s)\n' \
  "$GREEN" "$RESET" "$REQUIRED_REVIEWER_COUNT"

stage "Production database secret"
say "Use the direct or pooled production connection string for the cupedia-sg Supabase project."
open_url "https://supabase.com/dashboard/project/lisyyhruzlenzcehykrz/settings/database"
step "Copy the production PostgreSQL connection string and substitute the real database password."
warn "Do not paste it into chat, shell history, or a repository file."
ask_secret DATABASE_URL "Paste DATABASE_URL (hidden):"
if [[ "$DATABASE_URL" != postgres://* && "$DATABASE_URL" != postgresql://* ]]; then
  warn "DATABASE_URL must start with postgres:// or postgresql://."
  exit 1
fi
set_production_secret DATABASE_URL "$DATABASE_URL"
unset DATABASE_URL

stage "Production object-storage secrets"
say "Vercel can show these variable names but cannot reveal values marked Sensitive."
open_url "https://vercel.com/danhuang-s-projects/cupedia/settings/environment-variables"
step "Retrieve the authoritative values from the S3/MinIO provider or your password manager."
warn "Stop here rather than guessing or copying preview/local credentials."
ask_secret MINIO_ENDPOINT "Paste MINIO_ENDPOINT (hidden):"
ask_secret MINIO_REGION "Paste MINIO_REGION (hidden):"
ask_secret MINIO_ACCESS_KEY "Paste MINIO_ACCESS_KEY (hidden):"
ask_secret MINIO_SECRET_KEY "Paste MINIO_SECRET_KEY (hidden):"
ask_secret MINIO_BUCKET "Paste MINIO_BUCKET (hidden):"
ask_secret MINIO_PUBLIC_URL "Paste MINIO_PUBLIC_URL (hidden):"
for required_name in MINIO_ENDPOINT MINIO_REGION MINIO_ACCESS_KEY MINIO_SECRET_KEY MINIO_BUCKET MINIO_PUBLIC_URL; do
  if [[ -z "${!required_name}" ]]; then
    warn "$required_name cannot be empty. No object-storage secrets were changed."
    exit 1
  fi
done
set_production_secret MINIO_ENDPOINT "$MINIO_ENDPOINT"
set_production_secret MINIO_REGION "$MINIO_REGION"
set_production_secret MINIO_ACCESS_KEY "$MINIO_ACCESS_KEY"
set_production_secret MINIO_SECRET_KEY "$MINIO_SECRET_KEY"
set_production_secret MINIO_BUCKET "$MINIO_BUCKET"
set_production_secret MINIO_PUBLIC_URL "$MINIO_PUBLIC_URL"
unset MINIO_ENDPOINT MINIO_REGION MINIO_ACCESS_KEY MINIO_SECRET_KEY MINIO_BUCKET MINIO_PUBLIC_URL

stage "Dry-run and optional 10-person canary"
open_url "https://github.com/$REPOSITORY/actions/workflows/$WORKFLOW"
say "The first workflow run is database-only: dry-run, limit 10, concurrency 2."
gh workflow run "$WORKFLOW" --repo "$REPOSITORY" \
  -f mode=dry-run -f limit=10 -f concurrency=2
printf '  %s✓ started%s production dry-run\n' "$GREEN" "$RESET"
say "Watch the run in Actions and confirm it reports dryRun=true with no writes."
pause "Press Enter after the dry-run succeeds."
if confirm "Trigger the 10-person canary that writes database rows and WebP objects?"; then
  gh workflow run "$WORKFLOW" --repo "$REPOSITORY" \
    -f mode=canary -f limit=10 -f concurrency=2
  printf '  %s✓ started%s 10-person production canary\n' "$GREEN" "$RESET"
  open_url "https://github.com/$REPOSITORY/actions/workflows/$WORKFLOW"
  note "Verify the canary before selecting full mode. This wizard never starts full backfill."
else
  note "Canary not started. Re-run the workflow manually after reviewing the dry-run."
fi

finish
