// CUHK subject code → Chinese name.
//
// The catalog carries no subject-name/faculty column (#267), so this is a
// hand-curated lookup covering the departments/programmes we can name with
// confidence. Obscure programme codes are intentionally omitted — the UI falls
// back to the bare code rather than showing a guessed (possibly wrong) name.
// Extend as gaps are confirmed.
export const SUBJECT_NAMES: Record<string, string> = {
  ACCT: "会计学",
  AIST: "人工智能",
  ANTH: "人类学",
  ARAB: "阿拉伯文",
  ARCH: "建筑学",
  ARTS: "文学院",
  ASEI: "航天科学与地球信息学",
  BCHE: "生物化学",
  BIOL: "生物学",
  BMED: "生物医学",
  BMEG: "生物医学工程学",
  CHEM: "化学",
  CHLL: "中国语言及文学",
  COMM: "传播学",
  CSCI: "计算机科学",
  ECON: "经济学",
  EDUC: "教育学",
  ELEG: "电子工程学",
  ELTU: "大学英语",
  ENGE: "英文",
  ENGG: "工程学",
  ESSC: "地球系统科学",
  FAAS: "艺术",
  FINA: "金融学",
  FNSC: "食品及营养科学",
  FREN: "法文",
  FTEC: "金融科技",
  GERM: "德文",
  GLBS: "环球商业学",
  GPAD: "政治与行政学",
  HIST: "历史",
  HKSL: "香港手语",
  HTMG: "酒店及旅游管理学",
  IERG: "信息工程学",
  ITAL: "意大利文",
  JASP: "日本研究",
  KORE: "韩文",
  LAWS: "法律学",
  LING: "语言学",
  LSCI: "生命科学",
  MAEG: "机械与自动化工程学",
  MASE: "材料科学与工程学",
  MATH: "数学",
  MGNT: "管理学",
  MKTG: "市场学",
  MUSC: "音乐",
  NURS: "护理学",
  PHAR: "药剂学",
  PHED: "体育",
  PHIL: "哲学",
  PHPC: "公共卫生",
  PHYS: "物理",
  PSYC: "心理学",
  RMSC: "风险管理科学",
  RUSS: "俄文",
  SEEM: "系统工程与工程管理学",
  SOCI: "社会学",
  SOSC: "社会科学",
  SOWK: "社会工作",
  SPAN: "西班牙文",
  STAT: "统计学",
  THAI: "泰文",
  THEO: "神学",
  TRAN: "翻译",
  UGEA: "通识：中华文化传承",
  UGEB: "通识：自然、科技与环境",
  UGEC: "通识：社会与文化",
  UGED: "通识：自我与人文",
  UGFH: "与人文对话",
  UGFN: "与自然对话",
  URSP: "城市研究",
};
